"""add structured bug fields

Revision ID: 06647722f586
Revises: 90a8f73a605c
Create Date: 2026-06-15 14:45:39.805844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06647722f586'
down_revision = '90a8f73a605c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steps_to_reproduce', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('expected_result', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('actual_result', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('environment_os', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('environment_browser', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('environment_version', sa.String(length=50), nullable=True))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.drop_column('environment_version')
        batch_op.drop_column('environment_browser')
        batch_op.drop_column('environment_os')
        batch_op.drop_column('actual_result')
        batch_op.drop_column('expected_result')
        batch_op.drop_column('steps_to_reproduce')

    # ### end Alembic commands ###
