"""Table name fix reproduction

Revision ID: 54d8b38eba81
Revises: 63c7fa719a12
Create Date: 2026-06-09 13:10:47.972290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54d8b38eba81'
down_revision = '63c7fa719a12'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('reproduction_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bug_id', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.ENUM('REPRODUCED', 'NOT_REPRODUCED', name='result_attempt', create_type=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reporduction_attempts')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporduction_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bug_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result', postgresql.ENUM('REPRODUCED', 'NOT_REPRODUCED', name='result_attempt', create_type=False), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], name=op.f('reporduction_attempts_bug_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reporduction_attempts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reporduction_attempts_pkey'))
    )
    op.drop_table('reproduction_attempts')
    # ### end Alembic commands ###
